// Generated by Codex 5.3
const steps = ["one", "two", "three"];

// forEach
steps.forEach(function (item) {
  console.log(item);
});

// forEach (named function example)
// steps.forEach(showStep);
// function showStep(step) {
//   console.log(step);
// }

// map
const myList = document.querySelector("#myList");
const stepsHtml = steps.map(listTemplate);

function listTemplate(item) {
  return `<li>${item}</li>`;
}

myList.innerHTML = stepsHtml.join("");

// map - grades to points
let points;

function convert(grade) {
  switch (grade) {
    case "A":
      points = 4;
      break;
    case "B":
      points = 3;
      break;
    case "C":
      points = 2;
      break;
    case "D":
      points = 1;
      break;
    case "F":
      points = 0;
      break;
    default:
      alert("not a valid grade");
  }

  return points;
}

const grades = ["A", "B", "C"];
const gpaPoints = grades.map(convert);
console.log(gpaPoints);

// reduce
const totalPoints = gpaPoints.reduce(getTotal);

function getTotal(total, item) {
  return total + item;
}

console.log(totalPoints);

const gpaAverage = totalPoints / gpaPoints.length;
console.log(gpaAverage);

// filter
const words = ["watermelon", "peach", "apple", "tomato", "grape"];
const shortWords = words.filter(function (word) {
  return word.length < 6;
});
console.log(shortWords);

// indexOf
const myArray = [12, 34, 21, 54];
const luckyNumber = 21;
const luckyIndex = myArray.indexOf(luckyNumber);
console.log(luckyIndex);

// dynamic content with object array
const studentContainer = document.querySelector("#studentContainer");
const students = [
  { last: "Andrus", first: "Aaron" },
  { last: "Masa", first: "Manny" },
  { last: "Tanda", first: "Tamanda" }
];

students.forEach(function (item) {
  const name = document.createElement("div");
  name.className = "format";

  const studentHtml = `
    <span>${item.first}</span>
    <span>${item.last}</span>
    <hr>
  `;

  name.innerHTML = studentHtml;
  studentContainer.appendChild(name);
});

